services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "8000:8000"
    environment:
      CHOKIDAR_USEPOLLING: true
    volumes:
      - ./app:/web
      - /web/node_modules
