name: Deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the singleCycle branch
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: install dependencies
        run: |
          cd app
          npm install

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/proyecto/riscv-sim/ || { echo "Failed to change directory"; exit 1; }
            git pull || { echo "Git pull failed"; exit 1; }
            git status
            docker stop riscvsim
            docker rm riscvsim
            docker build -t riscvsimi . || { echo "Docker build failed"; exit 1; }
            docker run -d -it -p 5034:3000 --restart unless-stopped --name riscvsim riscvsimi || { echo "Docker run failed"; exit 1; }
